"""Reads test_plans.json and writes a literal, executable test.py — one real
pytest function per TestPlan, not a parametrized wrapper. test.py is
generated output: don't hand-edit it, edit the plans / prompts and re-run
this script instead.

Usage:
    python generate_test_file.py                     # reads ./test_plans.json -> ./test.py
    python generate_test_file.py plans.json out_test.py
"""
import json
import keyword
import re
import sys
from pathlib import Path
from string import Template

ROOT = Path(__file__).resolve().parent

HEADER = '''"""AUTO-GENERATED by generate_test_file.py from test_plans.json. Do not
hand-edit — regenerate with: python generate_test_file.py
"""
from _test_support import send_request, assert_response

'''

FUNC_TEMPLATE = Template('''
def $name():
    """$description"""
    resp = send_request(
        method=$method,
        path=$path,
        request_body=$request_body,
        content_type=$content_type,
    )
    assert resp.status_code == $expected_status_code, (
        f"expected $expected_status_code, got {resp.status_code} \u2014 body: {resp.text}"
    )
$response_assert

''')

FUNC_ASSERT_LINE = Template("    assert_response(resp.json(), $expected_response, context=$context)")


def _valid_identifier(raw_name: str, used: set[str]) -> str:
    """Turns a plan's name into a safe, unique, importable Python identifier.
    The planner prompt already asks for snake_case names prefixed with
    test_, so this is a safety net against odd LLM output, not the normal path."""
    ident = re.sub(r"\W", "_", raw_name) or "test_unnamed"
    if not ident.startswith("test_"):
        ident = f"test_{ident}"
    if keyword.iskeyword(ident):
        ident += "_"
    base, n = ident, 2
    while ident in used:
        ident = f"{base}_{n}"
        n += 1
    used.add(ident)
    return ident


def _render(plan: dict, name: str) -> str:
    expected_response = plan.get("expected_response")
    if expected_response:
        response_assert = FUNC_ASSERT_LINE.substitute(
            expected_response=repr(expected_response),
            context=repr(f"{name}: "),
        )
    else:
        response_assert = "    # no response body assertions for this scenario"

    description = (plan.get("description") or "").replace('"""', "'''").replace("\n", " ")

    return FUNC_TEMPLATE.substitute(
        name=name,
        description=description,
        method=repr(plan["method"]),
        path=repr(plan["path"]),
        request_body=repr(plan.get("request_body")),
        content_type=repr(plan.get("content_type", "application/json")),
        expected_status_code=repr(plan["expected_status_code"]),
        response_assert=response_assert,
    )


def generate(plans_path: Path, out_path: Path):
    plans = json.loads(plans_path.read_text(encoding="utf-8"))
    if not plans:
        print(f"No plans found in {plans_path} — nothing to generate.")
        return

    used_names: set[str] = set()
    chunks = [HEADER]
    for plan in plans:
        name = _valid_identifier(plan["name"], used_names)
        chunks.append(_render(plan, name))

    out_path.write_text("".join(chunks), encoding="utf-8")
    print(f"Wrote {len(plans)} test functions to {out_path}")


if __name__ == "__main__":
    plans_arg = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "test_plans.json"
    out_arg = Path(sys.argv[2]) if len(sys.argv) > 2 else ROOT / "test.py"
    if not plans_arg.exists():
        sys.exit(f"{plans_arg} not found. Run `python main.py --all --out {plans_arg}` first.")
    generate(plans_arg, out_arg)
