"""Reads test_plans.json and writes a literal, executable test.py — one real
pytest function per TestPlan, not a parametrized wrapper. test.py is
generated output: don't hand-edit it, edit the plans / prompts and re-run
this script instead.

Usage:
    python generate_test_file.py                     # reads ./test_plans.json -> ./test.py
    python generate_test_file.py plans.json out_test.py
"""
import json
import keyword
import re
import sys
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, StrictUndefined

try:
    from .plan_validation import validate_plans
except ImportError:  # pragma: no cover - direct-script compatibility
    from plan_validation import validate_plans

ROOT = Path(__file__).resolve().parent
TEMPLATES_DIR = ROOT / "templates"

HEADER = '''"""AUTO-GENERATED by generate_test_file.py from test_plans.json. Do not
hand-edit — regenerate with: python generate_test_file.py
"""
import pytest

from _test_support import send_request, assert_response

'''


def _pyrepr(value):
    """Jinja's default str-conversion mangles dicts/None/bools for Python
    source (e.g. True/None render fine, but plain str() on a dict uses
    single quotes inconsistently under some configs) — route everything
    through repr() explicitly so the rendered file is always valid,
    re-parseable Python literals."""
    return repr(value)


def _valid_identifier(raw_name: str, used: set[str]) -> str:
    """Turns a plan's name into a safe, unique, importable Python identifier.
    The planner prompt already asks for snake_case names prefixed with
    test_, so this is a safety net against odd LLM output, not the normal path."""
    ident = re.sub(r"\W", "_", raw_name) or "test_unnamed"
    if not ident.startswith("test_"):
        ident = f"test_{ident}"
    if keyword.iskeyword(ident):
        ident += "_"
    base, n = ident, 2
    while ident in used:
        ident = f"{base}_{n}"
        n += 1
    used.add(ident)
    return ident


def _make_env() -> Environment:
    env = Environment(
        loader=FileSystemLoader(TEMPLATES_DIR),
        undefined=StrictUndefined,  # fail loud on a missing plan field instead
                                     # of silently rendering "" into test.py
        trim_blocks=True,
        lstrip_blocks=True,
    )
    env.filters["pyrepr"] = _pyrepr
    return env


def _render(env: Environment, plan: dict, name: str, issues: list[str]) -> str:
    template = env.get_template("test_functinon.j2")
    description = str(plan.get("description") or "").replace('"""', "'''").replace("\n", " ")
    return template.render(
        name=name,
        description=description,
        invalid_reasons="Invalid plan: " + "; ".join(issues) if issues else None,
        method=plan.get("method"),
        path=plan.get("path"),
        request_body=plan.get("request_body"),
        content_type=plan.get("content_type", "application/json"),
        path_params=plan.get("path_params") or {},
        query_params=plan.get("query_params") or {},
        headers=plan.get("headers") or {},
        requires_api_key=plan.get("requires_api_key", False),
        requires_jwt=plan.get("requires_jwt", False),
        expected_status_code=plan.get("expected_status_code"),
        expected_response=plan.get("expected_response"),
    )


def generate(plans_path: Path, out_path: Path):
    plans = json.loads(plans_path.read_text(encoding="utf-8"))
    if not plans:
        print(f"No plans found in {plans_path} — nothing to generate.")
        return
    issues_by_plan = validate_plans(plans)

    env = _make_env()
    used_names: set[str] = set()
    chunks = [HEADER]
    for index, (plan, issues) in enumerate(zip(plans, issues_by_plan)):
        plan_dict = plan if isinstance(plan, dict) else {}
        raw_name = plan_dict.get("name") or f"plan_{index + 1}"
        name = _valid_identifier(str(raw_name), used_names)
        chunks.append(_render(env, plan_dict, name, issues))
        chunks.append("\n\n")

    out_path.write_text("".join(chunks), encoding="utf-8")
    print(f"Wrote {len(plans)} test functions to {out_path}")


if __name__ == "__main__":
    plans_arg = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "test_plans.json"
    out_arg = Path(sys.argv[2]) if len(sys.argv) > 2 else ROOT / "test.py"
    if not plans_arg.exists():
        sys.exit(f"{plans_arg} not found. Run `python main.py --all --out {plans_arg}` first.")
    generate(plans_arg, out_arg)
